const color = require('./colors');

/**
 * Token rules are deliberately split into two independent layers:
 *
 * 1. colorRule assigns foreground color only;
 * 2. decorationRule assigns font style only.
 *
 * This prevents a color from implicitly carrying italic, bold, or underline
 * styling. The stable order is defaults, palette colors, then decorations.
 */
const SCOPE_GROUP_ORDER = Object.freeze([
  'comment',
  'constant',
  'entity',
  'invalid',
  'keyword',
  'markup',
  'meta',
  'other',
  'property',
  'punctuation',
  'source',
  'storage',
  'string',
  'support',
  'tag',
  'text',
  'variable',
  '*',
]);

const SCOPE_GROUP_INDEX = new Map(
  SCOPE_GROUP_ORDER.map((group, index) => [group, index]),
);

function scopeGroup(scope) {
  const root = scope.match(/^[a-z]+/i)?.[0]?.toLowerCase() ?? '*';
  return SCOPE_GROUP_INDEX.has(root) ? root : '*';
}

function sortScopes(scopes) {
  return [...new Set(scopes)].sort((left, right) => {
    const groupDelta =
      SCOPE_GROUP_INDEX.get(scopeGroup(left)) -
      SCOPE_GROUP_INDEX.get(scopeGroup(right));
    return groupDelta || left.localeCompare(right, 'en');
  });
}

function colorRule(name, foreground, scopes) {
  return {
    name,
    scope: sortScopes(scopes),
    settings: { foreground },
  };
}

function decorationRule(name, fontStyle, scopes) {
  return {
    name,
    scope: sortScopes(scopes),
    settings: { fontStyle },
  };
}

const tokenColors = [
  // Provider-neutral fallbacks must remain first.
  colorRule('FALLBACK WHITE', color.white, [
    'entity.name.type',
    'support.type',
    // Punctuation
    'punctuation',
  ]),
  colorRule('FALLBACK OPERATOR', color.operator, [
    // Keywords and operators
    'keyword.operator',
    // Compound and wildcard selectors
    'operator',
  ]),
  colorRule('FALLBACK YELLOW', color.yellow, [
    // Keywords and operators
    'keyword',
    // Storage declarations
    'storage.modifier',
    'storage.type',
    // Support symbols
    'support.function',
  ]),
  colorRule('FALLBACK BLUE', color.blue, [
    'entity.name.function',
    // Variables
    'variable.other',
    'variable.parameter',
  ]),
  colorRule('FALLBACK PURPLE', color.purple, [
    // Meta scopes
    'meta.property-name',
  ]),

  // Palette rules follow. They set color only; styles are centralized below.
  colorRule('RED', color.red, [
    // Entities and declarations
    'entity.name.module.js',
    // Invalid and deprecated code
    'invalid',
    'invalid.illegal',
    // Markup
    'markup.bold.markdown',
    'markup.deleted',
    // Variables
    'variable.import.parameter.js',
    'variable.other.class.js',
  ]),
  colorRule('WHITE', color.white, [
    'entity.name.type.go',
    'entity.name.type.package.go',
    'entity.name.type.rust',
    'entity.name.type.struct.rust',
    'entity.name.type.struct.swift',
    'entity.name.type.swift',
    // Comments and documentation
    'comment.block.documentation.dart variable.other.source.dart',
    // Constants and literals
    'constant.other.color',
    // Entities and declarations
    'entity.name.function.close',
    'entity.name.tag.css.sass.symbol',
    'entity.name.tag.reference',
    'entity.name.tag.wildcard.css',
    'entity.name.tag.wildcard.sass',
    'entity.name.tag.wildcard.scss',
    'entity.other.attribute-name.pseudo-class',
    'entity.other.attribute-name.pseudo-class.css',
    'entity.other.attribute-name.pseudo-element.css',
    // Keywords and operators
    // 'keyword.control.c4',
    'keyword.control.unit.css.sass',
    'keyword.other.substitution',
    'keyword.other.template',
    // Markup
    'markup.raw.block.fenced.markdown',
    'markup.table',
    // Meta scopes
    'meta.brace.round',
    'meta.brace.square',
    'meta.declaration.dart',
    'meta.embedded.block.github-actions-expression',
    'meta.embedded.expression.js',
    'meta.embedded.expression.jsx',
    'meta.embedded.expression.ts',
    'meta.embedded.expression.tsx',
    'meta.function-call.arguments.python',
    'meta.import.ts punctuation.definition.block',
    'meta.import.ts punctuation.definition.block.ts',
    'meta.indexed-name.python',
    'meta.jsx.children.js.jsx',
    'meta.method.body.java',
    'meta.method.identifier.java variable.parameter.java',
    'meta.property-list.css',
    'meta.property-list.css.sass.prop comment',
    'meta.tag',
    'meta.type-name.swift',
    'meta.type.annotation.ts',
    'meta.type.annotation.tsx',
    // Other language scopes
    'other.source.dart',
    // Punctuation
    'punctuation.accessor.js',
    'punctuation.accessor.jsx',
    'punctuation.accessor.ts',
    'punctuation.accessor.tsx',
    'punctuation.bracket.angle.java',
    'punctuation.brackets.angle.rust',
    'punctuation.brackets.attribute.rust',
    'punctuation.brackets.curly.rust',
    'punctuation.brackets.round.rust',
    'punctuation.comma.rust',
    'punctuation.definition.attribute-selector.begin.bracket.square',
    'punctuation.definition.attribute-selector.end.bracket.square',
    'punctuation.definition.block.js',
    'punctuation.definition.bold.markdown',
    'punctuation.definition.dictionary.begin.json.comments',
    'punctuation.definition.entity',
    'punctuation.definition.interpolation.begin.bracket.curly.css',
    'punctuation.definition.interpolation.begin.bracket.curly.sass',
    'punctuation.definition.interpolation.begin.bracket.curly.scss',
    'punctuation.definition.interpolation.end.bracket.curly.css',
    'punctuation.definition.interpolation.end.bracket.curly.sass',
    'punctuation.definition.interpolation.end.bracket.curly.scss',
    'punctuation.definition.list_item.markdown',
    'punctuation.definition.map.begin.bracket.round.scss',
    'punctuation.definition.map.end.bracket.round.scss',
    'punctuation.definition.parameters.begin.bracket.round.scss',
    'punctuation.definition.parameters.begin.js',
    'punctuation.definition.parameters.end.bracket.round.scss',
    'punctuation.definition.parameters.end.js',
    'punctuation.dot.dart',
    'punctuation.section.class.end',
    'punctuation.section.embedded',
    'punctuation.section.function.begin.bracket.round.css',
    'punctuation.section.function.end.bracket.round.css',
    'punctuation.section.function.scss',
    'punctuation.section.property-list.begin.bracket.curly.css',
    'punctuation.section.property-list.begin.bracket.curly.sass',
    'punctuation.section.property-list.begin.bracket.curly.scss',
    'punctuation.section.property-list.end.bracket.curly.css',
    'punctuation.section.property-list.end.bracket.curly.sass',
    'punctuation.section.property-list.end.bracket.curly.scss',
    'punctuation.section.scope.begin.c4',
    'punctuation.section.scope.begin.swift',
    'punctuation.section.scope.end.c4',
    'punctuation.section.scope.end.swift',
    'punctuation.semi.rust',
    'punctuation.separator.comma',
    'punctuation.separator.comma.js',
    'punctuation.separator.delimiter.java',
    'punctuation.separator.inheritance.php',
    'punctuation.separator.java',
    'punctuation.separator.key-value.css',
    'punctuation.separator.key-value.html',
    'punctuation.separator.key-value.js',
    'punctuation.separator.key-value.mapping.yaml',
    'punctuation.separator.list.comma.css',
    'punctuation.separator.period.java',
    'punctuation.terminator.dart',
    'punctuation.terminator.java',
    'punctuation.terminator.rule.css',
    'punctuation.terminator.rule.sass',
    'punctuation.terminator.rule.scss',
    'punctuation.terminator.statement.js',
    'punctuation.terminator.statement.ts',
    'punctuation.terminator.statement.tsx',
    // Source roots
    'source.c4',
    'source.css',
    'source.css.sass',
    'source.css.scss',
    'source.dart',
    'source.go',
    'source.groovy',
    'source.java',
    'source.just',
    'source.makefile',
    'source.python',
    'source.ruby',
    'source.rust',
    'source.sass',
    'source.sass keyword.control',
    'source.sql',
    // Storage declarations
    'storage.modifier.import.java',
    'storage.modifier.package.java',
    'support.type.c4',
    'storage.type.boolean.go',
    'storage.type.numeric.go',
    'storage.type.string.go',
    // Strings
    'string.interpolated.single.dart meta.embedded.expression.dart variable.parameter.dart',
    // Support symbols
    'support.constant.mathematical-symbols.css',
    'support.constant.mathematical-symbols.sass',
    'support.constant.mathematical-symbols.scss',
    'support.function.name.sass.library',
    // Text
    'text.html.markdown',
    // Variables
    'variable.language.expanded-namespace.css',
    'variable.language.expanded-namespace.sass',
    'variable.language.expanded-namespace.scss',
    'variable.language.fenced.markdown',
    'variable.parameter.url.scss',
  ]),
  colorRule('OPERATOR', color.operator, ['storage.type.function.arrow']),
  colorRule('BROWN', color.brown, [
    // Entities and declarations
    'entity.name.tag',
    // Markup
    'markup.deleted.git_gutter',
    // Meta scopes
    'meta.tag.sgml',
    // Punctuation
    'punctuation.definition.tag',
  ]),
  colorRule('YELLOW', color.yellow, [
    // Selector prefixes are part of the selector, not neutral punctuation.
    'punctuation.definition.entity.css',
    'punctuation.definition.entity.sass',
    'punctuation.definition.entity.scss',
    // Comments and documentation
    'comment.block.documentation.dart variable.name.source.dart',
    // Constants and literals
    'constant.character',
    'constant.escape',
    'constant.language.boolean.false.js',
    'constant.language.boolean.false.jsx',
    'constant.language.boolean.false.ts',
    'constant.language.boolean.false.tsx',
    'constant.language.boolean.null.js',
    'constant.language.boolean.null.jsx',
    'constant.language.boolean.null.ts',
    'constant.language.boolean.null.tsx',
    'constant.language.boolean.true.js',
    'constant.language.boolean.true.jsx',
    'constant.language.boolean.true.ts',
    'constant.language.boolean.true.tsx',
    'constant.language.boolean.yaml',
    'constant.language.json.comments',
    'constant.language.null.js',
    'constant.other.color.rgb-value.hex',
    'constant.other.color.rgb-value.hex.css',
    // Entities and declarations
    'entity.name.function.scss',
    'entity.name.section.markdown',
    'entity.name.tag.css',
    'entity.name.typ.dart',
    'entity.name.type.class.java',
    'entity.name.type.class.python',
    'entity.name.type.js',
    'entity.name.type.module.js',
    'entity.name.type.primitive.rust',
    'entity.name.type.class.js',
    'entity.name.type.class.jsx',
    'entity.name.type.class.ts',
    'entity.name.type.class.tsx',
    'entity.other.attribute-name',
    'entity.other.attribute-name.attribute.css',
    'entity.other.attribute-name.attribute.sass',
    'entity.other.attribute-name.attribute.scss',
    'entity.other.attribute-name.class',
    'entity.other.attribute-name.class.sass',
    'entity.other.attribute-selector.sass',
    'entity.other.inherited-class',
    'entity.other.inherited-class.java',
    'entity.other.keyframe-offset.css',
    // Keywords and operators
    'keyword.control.c4',
    'keyword.control.await.swift',
    'keyword.control.catch-exception.dart',
    'keyword.control.catch.java',
    'keyword.control.conditional.js',
    'keyword.control.conditional.jsx',
    'keyword.control.conditional.ts',
    'keyword.control.conditional.tsx',
    'keyword.control.dart',
    'keyword.control.default.js.jsx',
    'keyword.control.exception.swift',
    'keyword.control.export.js',
    'keyword.control.export.jsx',
    'keyword.control.export.ts',
    'keyword.control.export.tsx',
    'keyword.control.flow.js',
    'keyword.control.flow.jsx',
    'keyword.control.flow.python',
    'keyword.control.flow.ts',
    'keyword.control.flow.tsx',
    'keyword.control.from.js',
    'keyword.control.from.jsx',
    'keyword.control.from.ts',
    'keyword.control.from.tsx',
    'keyword.control.go',
    'keyword.control.groovy',
    'keyword.control.if.css',
    'keyword.control.if.css punctuation.definition.keyword.css',
    'keyword.control.if.sass',
    'keyword.control.if.sass punctuation.definition.keyword.sass',
    'keyword.control.if.scss',
    'keyword.control.if.scss punctuation.definition.keyword.scss',
    'keyword.control.import.go',
    'keyword.control.import.js',
    'keyword.control.import.jsx',
    'keyword.control.import.python',
    'keyword.control.import.ts',
    'keyword.control.import.tsx',
    'keyword.control.java',
    'keyword.control.loop.js',
    'keyword.control.new.groovy',
    'keyword.control.new.java',
    'keyword.control.operator',
    'keyword.control.pseudo-method.ruby',
    'keyword.control.return.css punctuation.definition.keyword.css',
    'keyword.control.return.dart',
    'keyword.control.return.sass',
    'keyword.control.return.sass punctuation.definition.keyword.sass',
    'keyword.control.return.scss',
    'keyword.control.return.scss punctuation.definition.keyword.scss',
    'source.sass keyword.control.at-rule.css.sass',
    'keyword.control.ruby',
    'keyword.control.rust',
    'keyword.control.start-block.ruby',
    'keyword.control.transfer.swift',
    'keyword.control.try.java',
    'keyword.control.trycatch.js',
    'keyword.control.trycatch.jsx',
    'keyword.control.trycatch.ts',
    'keyword.control.trycatch.tsx',
    'keyword.function.go',
    'keyword.operator.expression.of.js',
    'keyword.operator.expression.typeof.js',
    'keyword.operator.instanceof.java',
    'keyword.operator.logical.python',
    'keyword.operator.new.js',
    'keyword.operator.new.jsx',
    'keyword.operator.new.ts',
    'keyword.operator.new.tsx',
    'keyword.other.declaration-specifier.accessibility.swift',
    'keyword.other.declaration-specifier.swift',
    'keyword.other.fn.rust',
    'keyword.other.rust',
    'keyword.other.special-method',
    'keyword.other.special-method.ruby',
    'keyword.other.unit',
    'keyword.other.DDL.create.II.sql',
    'keyword.other.DML.sql',
    'keyword.other.LUW.sql',
    'keyword.other.create.sql',
    'keyword.other.sql',
    'keyword.package.go',
    'keyword.struct.go',
    'keyword.type.go',
    'keyword.var.go',
    // Markup
    'markup.changed.git_gutter',
    'markup.heading.markdown',
    // Meta scopes
    'meta.at-rule.if',
    'meta.at-rule.mixin',
    'meta.block.js meta.block.js new.expr.js meta.function-call.js',
    'meta.block.js variable.other.object.js',
    'meta.block.jsx meta.block.jsx new.expr.jsx meta.function-call.jsx',
    'meta.block.jsx variable.other.object.jsx',
    'meta.block.ts meta.block.ts new.expr.ts meta.function-call.ts',
    'meta.block.ts variable.other.object.ts',
    'meta.block.tsx meta.block.tsx new.expr.tsx meta.function-call.tsx',
    'meta.block.tsx variable.other.object.tsx',
    'meta.catch.parameters.java storage.type.java',
    'meta.definition.variable.java storage.type.generic.java',
    'meta.definition.variable.java storage.type.java',
    'meta.definition.variable.java storage.type.primitive.array.java',
    'meta.export.default',
    'meta.export.default.ts',
    'meta.export.default.ts meta.array.literal.ts',
    'meta.field.declaration.ts',
    'meta.field.declaration.tsx',
    'meta.function-call.swift meta.function-call.swift support.function.any-method.swift',
    'meta.function.js',
    'meta.function.jsx',
    'meta.function.ts',
    'meta.function.tsx',
    'meta.import',
    'meta.import.ts',
    'meta.method.identifier.java storage.type.java',
    'meta.property-list',
    'meta.property-list.css.sass.prop keyword.control.unit.css.sass',
    'meta.property-list.sass',
    'meta.property-list.scss',
    'meta.property-value',
    'meta.property-value.css',
    'meta.property-value.sass',
    'meta.property-value.scss',
    'meta.try.body.java storage.type.java',
    'meta.use.php',
    'meta.var.expr.ts',
    'meta.var.expr.tsx',
    // Properties
    'property.value.dotenv',
    // Punctuation
    'punctuation.definition.block.tsx',
    'punctuation.definition.constant',
    'punctuation.definition.constant.css',
    'punctuation.definition.directive.c',
    // Storage declarations
    'storage.modifier',
    'storage.modifier.async.swift',
    'storage.modifier.attribute.swift',
    'storage.modifier.exception.swift',
    'storage.modifier.mut.rust',
    'storage.modifier.sql',
    'storage.modifier.swift',
    'storage.modifier.ts',
    'storage.modifier.tsx',
    'storage.type',
    'storage.type.def.groovy',
    'storage.type.function',
    'storage.type.groovy',
    'storage.type.primitive.dart',
    'storage.type.primitive.java',
    'storage.type.rust',
    'storage.type.sql',
    // Support symbols
    'support.class',
    'support.class.builtin.js',
    'support.class.dart',
    'support.constant',
    'support.constant.font-name',
    'support.constant.property-value',
    'support.constant.property-value.css',
    'support.function',
    'support.function.misc.scss',
    'support.orther.namespace.use.php',
    'support.other.namespace.php',
    'support.type.builtin.ts',
    'support.type.builtin.tsx',
    'support.type.exception.python',
    'support.type.object.module.js',
    'support.type.property-name.css meta.property-value.css',
    'support.type.property-name.sass meta.property-value.sass',
    'support.type.property-name.scss meta.property-value.scss',
    'support.type.python',
    'support.type.sys-types',
    // Text
    'text.html.basic entity.other.attribute-name',
    'text.html.basic entity.other.attribute-name.html',
    // Variables
    'variable.function',
    'variable.language',
    'variable.language.dart',
    'variable.language.self.rust',
    'variable.language.this',
    'variable.language.this.java',
    'variable.other.constant.object.js',
    'variable.other.constant.object.jsx',
    'variable.other.constant.object.ts',
    'variable.other.constant.object.tsx',
    'variable.other.object.java',
    'variable.other.object.js',
    'variable.other.object.jsx',
    'variable.other.object.ts',
    'variable.other.object.tsx',
    'variable.parameter.url',
  ]),
  colorRule('ORANGE', color.orange, [
    // Constants and literals
    'constant.character',
    'constant.language',
    'constant.language.color.rgb-value.css.sass',
    'constant.language.dart',
    'constant.numeric',
    'constant.numeric.css',
    'constant.numeric.decimal.js',
    // Entities and declarations
    'entity.name.type.numeric.rust',
    // Keywords and operators
    'keyword.other.unit.ch.css',
    'keyword.other.unit.cm.css',
    'keyword.other.unit.deg.css',
    'keyword.other.unit.em.css',
    'keyword.other.unit.ex.css',
    'keyword.other.unit.in.css',
    'keyword.other.unit.mm.css',
    'keyword.other.unit.pc.css',
    'keyword.other.unit.percentage.css',
    'keyword.other.unit.pt.css',
    'keyword.other.unit.px',
    'keyword.other.unit.px.css',
    'keyword.other.unit.rem.css',
    'keyword.other.unit.s',
    'keyword.other.unit.s.css',
    'keyword.other.unit.vh.css',
    'keyword.other.unit.vmax.css',
    'keyword.other.unit.vmin.css',
    'keyword.other.unit.vw.css',
    // Property
    'property.value.dotenv',
    // Support symbols
    'support.constant',
    // Variables
    'variable.parameter.function.language.special',
  ]),
  colorRule('BLUE', color.blue, [
    'entity.name.function.js',
    'entity.name.function.jsx',
    'entity.name.function.ts',
    'entity.name.function.tsx',
    // Constants and literals
    'constant.other.caps.python',
    'constant.other.caps.rust',
    'constant.other.php',
    // Entities and declarations
    'entity.name.function.ruby',
    'entity.name.function.sql',
    'entity.name.method.js',
    'entity.name.namespace.rust',
    'entity.name.section.toml',
    // Keywords and operators
    'keyword.control.at-rule.font-face.css',
    'keyword.control.at-rule.import',
    'keyword.control.at-rule.import.css',
    'keyword.control.at-rule.include.css',
    'keyword.control.at-rule.include.sass',
    'keyword.control.at-rule.include.scss',
    'keyword.control.at-rule.keyframes.css',
    'keyword.control.at-rule.keyframes.sass',
    'keyword.control.at-rule.keyframes.scss',
    'keyword.control.at-rule.media',
    'keyword.control.at-rule.media.css',
    'keyword.control.at-rule.mixin',
    'keyword.control.at-rule.supports.css',
    'keyword.control.at-rule.use.scss',
    'keyword.declaration.dart',
    'keyword.other.import.dart',
    'keyword.other.crate.rust',
    'keyword.other.import.java',
    'keyword.other.package.java',
    // Markup
    'markup.quote punctuation.definition.blockquote.markdown',
    'markup.underline.link.markdown',
    // Meta scopes
    'meta.arrow.tsx',
    'meta.at-rule.function.css',
    'meta.at-rule.function.sass',
    'meta.at-rule.function.scss',
    'meta.at-rule.include.css',
    'meta.at-rule.include.sass',
    'meta.at-rule.include.scss',
    'meta.at-rule.keyframes.css',
    'meta.at-rule.keyframes.sass',
    'meta.at-rule.keyframes.scss',
    'meta.at-rule.supports.css',
    'meta.at-rule.supports.sass',
    'meta.at-rule.supports.scss',
    'meta.at-rule.use.css',
    'meta.at-rule.use.sass',
    'meta.at-rule.use.scss',
    'meta.attribute.rust',
    'meta.block.js meta.var.expr.js variable.other.object.js',
    'meta.block.jsx meta.var.expr.jsx variable.other.object.jsx',
    'meta.block.ts meta.var.expr.ts variable.other.object.ts',
    'meta.block.tsx',
    'meta.block.tsx meta.var.expr.tsx variable.other.object.tsx',
    'meta.class-method.js',
    'meta.definition.function.js',
    'meta.definition.variable.css',
    'meta.definition.variable.groovy',
    'meta.definition.variable.name.groovy',
    'meta.definition.variable.sass',
    'meta.embedded.line',
    'meta.fstring.python',
    'meta.function-call.java',
    'meta.function.decorator.python',
    'meta.function.decorator.python support.type.python',
    'meta.function.js meta.block.js meta.function.js meta.block.js meta.block.js variable.other.object.js',
    'meta.function.jsx meta.block.jsx meta.function.jsx meta.block.jsx meta.block.jsx variable.other.object.jsx',
    'meta.function.ts meta.block.ts meta.function.ts meta.block.ts meta.block.ts variable.other.object.ts',
    'meta.function.tsx meta.block.tsx meta.function.tsx meta.block.tsx meta.block.tsx variable.other.object.tsx',
    'meta.property-list.css meta.at-rule.include.css',
    'meta.property-list.css variable.css',
    'meta.property-list.sass meta.at-rule.include.sass',
    'meta.property-list.sass variable.sass',
    'meta.property-list.scss meta.at-rule.include.scss',
    'meta.property-list.scss variable.scss',
    'meta.property-value.css variable.css',
    'meta.property-value.sass variable.sass',
    'meta.property-value.scss variable.scss',
    'meta.require.ruby',
    'meta.use.rust',
    'meta.var-single-variable.expr.js',
    'meta.var.expr.js',
    'meta.var.expr.ts',
    'meta.var.expr.ts meta.definition.variable.ts',
    'meta.var.expr.tsx meta.definition.variable.tsx',
    // Punctuation
    'punctuation.definition.annotation.java',
    'punctuation.definition.keyword',
    'punctuation.definition.keyword.css',
    // Source roots
    // Storage declarations
    'storage.modifier.dart',
    'storage.modifier.implements.java',
    'storage.modifier.java',
    'storage.type.annotation.dart',
    'storage.type.annotation.java',
    'storage.type.class.python',
    'storage.type.function.python',
    // Strings
    'string.interpolated.single.dart variable.parameter.dart',
    'string.other.link',
    'string.other.link.title.markdown',
    // Support symbols
    'support.function.target.PHONY.makefile',
    'support.other.variable',
    // Tags
    'tag.decorator.js entity.name.tag.js',
    'tag.decorator.js punctuation.definition.tag.js',
    // Text
    'text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown',
    // Variables
    'variable.argument.css',
    'variable.css',
    'variable.function.constructor',
    'variable.key.dotenv',
    'variable.language.arguments.js',
    'variable.language.fenced.markdown',
    'variable.language.ruby',
    'variable.language.special.self.python',
    'variable.other.assignment.go',
    'variable.other.block.ruby',
    'variable.other.constant.js',
    'variable.other.constant.jsx',
    'variable.other.constant.ruby',
    'variable.other.constant.ts',
    'variable.other.constant.tsx',
    'variable.other.env',
    'variable.other.go',
    'variable.other.just',
    'variable.other.makefile',
    'variable.other.read.github-actions-expression',
    'variable.other.readwrite.alias.js',
    'variable.other.readwrite.alias.ts',
    'variable.other.readwrite.alias.tsx',
    'variable.other.readwrite.js',
    'variable.other.readwrite.ts',
    'variable.other.readwrite.tsx',
    'variable.other.rust',
    'variable.other.swift',
    'variable.parameter.function.language.special',
    'variable.parameter.js',
    'variable.parameter.ts',
    'variable.parameter.tsx',
    'variable.ruby',
    'variable.sass',
    'variable.scss',
  ]),
  colorRule('GREEN', color.green, [
    // Constants and literals
    'constant.character.escape',
    'constant.numeric.hex.toml',
    'constant.other.date.toml',
    'constant.other.key',
    'constant.other.symbol',
    // Entities and declarations
    'entity.other.inherited-class',
    // Keywords and operators
    'keyword.operator.negation.regexp',
    'keyword.other.js',
    // Markup
    'markup.heading',
    'markup.heading | markup.heading entity.name',
    'markup.inserted',
    'markup.inserted.git_gutter',
    // Meta scopes
    'meta.attribute-selector.css',
    'meta.attribute-selector.sass',
    'meta.attribute-selector.scss',
    'meta.embedded.expression.dart',
    'meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js',
    // Punctuation
    'punctuation.definition.character-class.regexp',
    'punctuation.definition.string',
    'punctuation.definition.string.begin.css',
    'punctuation.definition.string.begin.html',
    'punctuation.definition.string.begin.js',
    'punctuation.definition.string.end.css',
    'punctuation.definition.string.end.html',
    'punctuation.definition.string.end.js',
    'punctuation.definition.template-expression',
    // Source roots
    // Strings
    'string',
    'string.interpolated.single.dart',
    'string.json.comments',
    'string.regexp',
    'string.regexp.js',
    'string.regexp.ts',
    // Compound and wildcard selectors
    '*link*',
    '*uri*',
    '*url*',
  ]),
  colorRule('PURPLE', color.purple, [
    'entity.name.function.dart',
    'entity.name.function.go',
    'entity.name.function.java',
    'entity.name.function.macro.rust',
    'entity.name.function.python',
    'entity.name.function.rust',
    'entity.name.function.target.just',
    'entity.name.function.target.makefile',
    // Calls remain distinct from declarations when the grammar exposes them.
    'meta.function-call entity.name.function',
    'meta.method-call entity.name.function',
    ...['js', 'jsx', 'ts', 'tsx'].flatMap((language) => [
      `meta.function-call.${language} entity.name.function.${language}`,
      `meta.method-call.${language} entity.name.function.${language}`,
    ]),
    // Comments and documentation
    'comment.line.shebang.js',
    // Constants and literals
    'constant.other.reference.link.markdown',
    // Entities and declarations
    'entity.name.function.css',
    'entity.name.function.sass',
    'entity.name.function.support.go',
    'entity.name.tag.yaml',
    // Invalid and deprecated code
    'invalid.deprecated',
    // Keywords and operators
    // Markup
    'markup.bold markup.italic',
    'markup.bold markup.italic string',
    'markup.changed',
    'markup.italic markup.bold',
    'markup.italic markup.bold string',
    'markup.quote markup.bold',
    'markup.quote markup.bold string',
    'markup.raw.block',
    // Meta scopes
    'meta.attribute.python',
    'meta.create.sql',
    'meta.definition.function.body.swift storage.type.function.swift',
    'meta.definition.method.ts',
    'meta.export.default meta.object.member',
    'meta.export.default.ts meta.object.member.ts',
    'meta.function-call.js',
    'meta.function-call.jsx',
    'meta.function-call.python',
    'meta.function-call.ruby entity.name.function.ruby',
    'meta.function-call.ts',
    'meta.function-call.tsx',
    'meta.function.definition.rust',
    'meta.method-call.groovy',
    'meta.object-literal.key',
    'meta.object.member',
    'meta.object.member.js',
    'meta.property-list.css entity.name.tag.css',
    'meta.property-list.sass entity.name.tag.sass',
    'meta.property-list.scss entity.name.tag.scss',
    'meta.property-name',
    'meta.property-name.css',
    'meta.property-name.sass',
    'meta.property-name.scss',
    'meta.tag.metadata.doctype.html entity.name.tag',
    'meta.tag.metadata.doctype.html entity.other.attribute-name.html',
    'meta.tag.metadata.doctype.html punctuation.definition.tag.begin.html',
    'meta.tag.metadata.doctype.html punctuation.definition.tag.end.html',
    'meta.var.expr.tsx meta.arrow.tsx',
    'meta.var.expr.tsx meta.block.tsx',
    // Punctuation
    'punctuation.definition.constant.markdown',
    // Source roots
    'source.js',
    // Strings
    'string.other.link.description.title.markdown',
    // Support symbols
    'support.function.any-method.swift',
    'support.function.calc.css',
    'support.function.github-actions-expression',
    'support.function.magic.python',
    'support.function.misc.css',
    'support.function.misc.sass',
    'support.type.property-name.css',
    'support.type.property-name.json',
    'support.type.property-name.toml',
    'support.type.property-name.css.sass.prop.name',
    'support.type.property-name.media.css',
    'support.variable.property.js',
    'support.variable.property.tsx',
    'support.variable.property.tx',
    // Text
    'text.html.markdown markup.inline.raw.markdown',
    // Variables
    'variable.object.property.js',
    'variable.object.property.ts',
    'variable.object.property.tsx',
    'variable.other.constant.property.js',
    'variable.other.constant.property.jsx',
    'variable.other.constant.property.ts',
    'variable.other.constant.property.tsx',
    'variable.other.key.toml',
    'variable.other.object.property',
    'variable.other.object.property.js',
    'variable.other.object.property.tsx',
    'variable.other.property',
    'variable.other.property.go',
    'variable.other.property.c4',
  ]),
  colorRule('GREY', color.gray, [
    // Comments and documentation
    'comment',
    'punctuation.definition.comment',
    'punctuation.definition.comment.c',
    'comment.line.number-sign.yaml entity.name.tag.yaml',
    'comment.line.number-sign.yaml meta.embedded.block.github-actions-expression',
    'comment.line.number-sign.yaml punctuation.separator.key-value.mapping.yaml',
    'comment.line.number-sign.yaml string',
    'comment.line.number-sign.yaml variable.other.read.github-actions-expression',
    // Markup
    'markup.raw.block.fenced.markdown',
    // Punctuation
    'punctuation.definition.comment.go.mod',
    'punctuation.definition.fenced.markdown',
  ]),

  // CodePen's TypeScript cm-type is unstyled (white), unlike cm-keyword.
  // Scope these corrections to TS so they cannot recolor other languages.
  colorRule('TYPESCRIPT TYPES', color.white, [
    'punctuation.definition.block.tsx',
    'meta.import.tsx punctuation.definition.block.tsx',
    'source.ts entity.name.type',
    'source.tsx entity.name.type',
    'source.ts support.type',
    'source.tsx support.type',
    'keyword.operator.type.annotation.ts',
    'keyword.operator.type.annotation.tsx',
  ]),
  colorRule('TYPESCRIPT IMPORT MODIFIER', color.blue, [
    'meta.import.ts keyword.control.type',
    'meta.import.tsx keyword.control.type',
  ]),
  colorRule('TYPESCRIPT TYPE OPERATORS', color.operator, [
    'punctuation.definition.typeparameters.begin.ts',
    'punctuation.definition.typeparameters.end.ts',
    'punctuation.definition.typeparameters.begin.tsx',
    'punctuation.definition.typeparameters.end.tsx',
  ]),

  // Shared roles measured in the classic JS/TS editor. Language grammars
  // retain ownership of context; semantic tokens refine ambiguous identifiers.
  colorRule('TWILIGHT TYPE REFERENCES', color.white, [
    'storage.type.built-in.c',
    'storage.type.built-in.primitive.c',
    'storage.type.built-in.primitive.cpp',
    'source.cs keyword.type',
    'support.type.builtin.ts',
    'support.type.builtin.tsx',
    'support.class',
    'support.class.dart',
    'support.type.python',
    'support.type.exception.python',
    'support.type.sys-types',
    'storage.type.primitive.dart',
    'storage.type.primitive.java',
    'storage.type.java',
    'storage.type.generic.java',
    'storage.type.object.array.java',
    'keyword.other.type.php',
    'meta.parameter-clause.swift',
    'meta.method.return-type.java storage.type.java',
    'meta.method.identifier.java storage.type.java',
    'meta.definition.variable.java storage.type.java',
    'meta.definition.variable.java storage.type.generic.java',
    'meta.catch.parameters.java storage.type.java',
    'meta.try.body.java storage.type.java',
    'entity.name.type.primitive.rust',
    'entity.name.type.numeric.rust',
    'entity.other.inherited-class',
    'entity.other.inherited-class.java',
    ...['js', 'jsx', 'ts', 'tsx'].map(
      (language) => `entity.other.inherited-class.${language}`,
    ),
  ]),
  colorRule('TWILIGHT DECLARATIONS', color.blue, [
    'string.interpolated.escaping.just',
    'variable.language.makefile',
    'entity.name.variable.parameter.cs',
    'entity.name.variable.local.cs',
    'meta.method.identifier.java variable.parameter.java',
    'entity.name.type.class',
    'entity.name.type.interface',
    'entity.name.type.enum',
    'entity.name.type.struct',
    'entity.name.function.go',
    'entity.name.function.python',
    'entity.name.function.rust',
    'entity.name.type.class.java',
    'entity.name.type.record.java',
    'entity.name.type.class.python',
    'entity.name.type.actor.swift',
    'entity.name.type.anchor.yaml',
    'entity.name.type.protocol.swift',
    'entity.name.type.struct.rust',
    'entity.name.type.trait.rust',
    'meta.definition.type.struct.swift entity.name.type.struct.swift',
    'meta.parameter-clause.swift variable.parameter.function.swift',
    'meta.parameter-clause.swift entity.name.function.swift',
    ...['js', 'jsx', 'ts', 'tsx'].flatMap((language) => [
      `entity.name.type.class.${language}`,
      `entity.name.type.interface.${language}`,
      `entity.name.type.enum.${language}`,
      `meta.enum.declaration.${language} variable.other.enummember.${language}`,
    ]),
  ]),
  colorRule('TWILIGHT MEMBERS', color.purple, [
    'entity.name.function.just',
    'variable.name.alias.just',
    'meta.function.method.with-arguments.ruby entity.name.function.ruby',
    'meta.function.method.without-arguments.ruby entity.name.function.ruby',
    'entity.name.function.target.makefile',
    'support.function.target.PHONY.makefile',
    'meta.scope.prerequisites.makefile',
    'meta.scope.prerequisites.makefile constant.other.placeholder.makefile',
    'entity.name.variable.property.cs',
    'entity.name.variable.field.cs',
    'entity.name.function.member.cpp',
    'meta.body.struct.cpp meta.head.function.definition.cpp entity.name.function.definition.cpp',
    'meta.body.class.cpp meta.head.function.definition.cpp entity.name.function.definition.cpp',
    'meta.body.struct.cpp > meta.declaration.cpp variable.other.declare.cpp',
    'meta.body.class.cpp > meta.declaration.cpp variable.other.declare.cpp',
    'meta.body.struct.cpp > meta.declaration.cpp meta.declaration.cpp variable.other.declare.cpp',
    'meta.body.class.cpp > meta.declaration.cpp meta.declaration.cpp variable.other.declare.cpp',
    'meta.class.body.java > meta.definition.variable.java variable.other.definition.java',
    'meta.record.identifier.java',
    'meta.class.body.php meta.function.php > entity.name.function.php',
    'meta.function.parameter.promoted-property.php variable.other.php',
    'meta.definition.type.body.swift meta.definition.function.swift > entity.name.function.swift',
    'meta.function-call.swift support.function.any-method.swift',
    'meta.function-call.swift meta.function-call.swift support.function.any-method.swift',
    'meta.function.call.rust entity.name.function.rust',
    'support.type.property-name.table.toml',
    'support.type.property-name.array.toml',
    'entity.name.function.cs',
    'meta.body.class.cpp entity.name.function.call.cpp',
    'entity.name.function.java',
    'entity.name.function.dart',
    ...['js', 'js.jsx', 'jsx', 'ts', 'tsx'].flatMap((language) => [
      `meta.definition.method.${language} entity.name.function.${language}`,
      `meta.method.declaration.${language} > storage.type.${language}`,
      `meta.object-literal.key.${language} entity.name.function.${language}`,
      `meta.object.member.${language} variable.other.readwrite.${language}`,
      `meta.function-call.${language} entity.name.function.${language}`,
      `support.variable.property.${language}`,
      `variable.other.enummember.${language}`,
    ]),
  ]),
  colorRule('TWILIGHT KEYWORDS AND ATOMS', color.yellow, [
    'constant.language',
    'constant.language.color.rgb-value.css.sass',
    'meta.directive.on.svelte entity.name.type.svelte',
    'constant.language.dart',
    'storage.modifier.dart',
    'storage.type.annotation.dart',
    'storage.modifier.java',
    'storage.modifier.implements.java',
    'keyword.operator.sizeof.c',
    'keyword.operator.expression.new.cs',
    'keyword.operator.as.php',
    'entity.name.function.support.builtin.go',
    'entity.name.function.decorator.python',
    'keyword.declaration.dart',
    'keyword.other.import.dart',
    'keyword.other.import.java',
    'keyword.other.package.java',
    'storage.type.class.python',
    'storage.type.function.python',
    ...['js', 'js.jsx', 'jsx', 'ts', 'tsx'].flatMap((language) => [
      `keyword.operator.expression.${language}`,
      `keyword.operator.expression.typeof.${language}`,
      `keyword.operator.expression.instanceof.${language}`,
      `keyword.operator.expression.keyof.${language}`,
      `keyword.operator.expression.infer.${language}`,
      `keyword.operator.expression.in.${language}`,
      `keyword.operator.expression.of.${language}`,
      `keyword.operator.expression.is.${language}`,
      `keyword.operator.type.asserts.${language}`,
      `meta.namespace.declaration.${language} entity.name.type.module.${language}`,
      `new.expr.${language} meta.function-call.${language} entity.name.function.${language}`,
      `meta.export.${language} variable.other.readwrite.alias.${language}`,
      `meta.decorator.${language} variable.other.readwrite.${language}`,
      `constant.character.entity.${language}`,
      `constant.character.entity.${language} punctuation.definition.entity.${language}`,
    ]),
    'source.js entity.other.inherited-class.js',
    'source.js support.class.promise.js',
  ]),
  colorRule('TWILIGHT SPREAD', color.purple, [
    'keyword.operator.rest.js',
    'keyword.operator.rest.jsx',
    'keyword.operator.rest.ts',
    'keyword.operator.rest.tsx',
    'keyword.operator.spread.js',
    'keyword.operator.spread.jsx',
    'keyword.operator.spread.ts',
    'keyword.operator.spread.tsx',
  ]),
  colorRule('TWILIGHT REGEX', color.green, [
    'string.regexp keyword.operator.quantifier.regexp',
    'string.regexp.js keyword.other.js',
    'string.regexp.ts keyword.other.ts',
    'string.regexp.tsx keyword.other.tsx',
  ]),
  colorRule('TWILIGHT BIGINT', color.orange, ['storage.type.numeric.bigint']),
  colorRule('TWILIGHT JSX TAGS', color.brown, [
    'entity.name.tag support.class.component',
  ]),
  colorRule('TWILIGHT JSX PUNCTUATION', color.white, [
    ...['js', 'js.jsx', 'jsx', 'tsx'].map(
      (language) =>
        `meta.tag.attributes.${language} keyword.operator.assignment.${language}`,
    ),
  ]),
  colorRule('TWILIGHT DECORATOR PUNCTUATION', color.operator, [
    'punctuation.decorator.ts',
    'punctuation.decorator.tsx',
  ]),
  colorRule('TWILIGHT DOCUMENTATION', color.gray, [
    'comment.block.documentation.dart variable.name.source.dart',
    'comment.block.documentation.dart variable.other.source.dart',
    'comment.block.documentation punctuation',
    'comment.block.documentation storage.type.class.jsdoc',
    'comment.block.documentation punctuation.definition.block.tag.jsdoc',
    'comment.block.documentation entity.name.type.instance.jsdoc',
    'comment.block.documentation punctuation.definition.bracket.curly.begin.jsdoc',
    'comment.block.documentation punctuation.definition.bracket.curly.end.jsdoc',
    'comment.block.documentation variable.other.jsdoc',
  ]),
  // Documentation markup must remain visible inside the muted comment body.
  // Runtime refinement supplies the same roles when a grammar exposes only a
  // single undifferentiated comment token.
  colorRule('DOCUMENTATION CODE', color.white, [
    'comment markup.inline.raw',
    'comment punctuation.definition.raw',
    'comment.block.documentation.dart punctuation',
    'comment.block.documentation.dart variable.other.source.dart',
  ]),
  colorRule('DOCUMENTATION MEMBER REFERENCE', color.purple, [
    'comment.block.documentation.dart variable.name.source.dart',
  ]),
  colorRule('TWILIGHT STRING PARTS', color.green, [
    'string constant.other.placeholder',
    'property.value.dotenv',
    'keyword.interpolation.begin.dotenv',
    'keyword.interpolation.end.dotenv',
    'string.interpolated.escape.just',
    'storage.type.string.python',
    'constant.character.format.placeholder.other.python',
    'constant.other.placeholder.go',
    'string.quoted.single.char.rust punctuation.definition.char.rust',
    'punctuation.definition.interpolation.begin.cs',
    'punctuation.definition.interpolation.end.cs',
    'punctuation.section.embedded.begin.swift',
    'punctuation.section.embedded.end.swift',
    'punctuation.definition.interpolation.rust',
    'punctuation.section.embedded.begin.ruby',
    'punctuation.section.embedded.end.ruby',
    'punctuation.section.embedded.end.ruby source.ruby',
    'string.quoted.double.php punctuation.definition.variable.php',
    'string.quoted.double.shell punctuation.definition.variable.shell',
    'string.quoted.double.shell punctuation.definition.variable.shell variable.other.normal.shell',
  ]),
  colorRule('TWILIGHT UNITS', color.orange, [
    'constant.numeric.css keyword.other.unit',
    'meta.property-list.css.sass.prop keyword.control.unit.css.sass',
  ]),
  colorRule('TWILIGHT TYPE PUNCTUATION', color.operator, [
    'storage.modifier.reference.cpp',
    'punctuation.section.angle-brackets.begin.template.call.cpp',
    'punctuation.section.angle-brackets.end.template.call.cpp',
    'punctuation.bracket.angle.java',
    'punctuation.brackets.angle.rust',
    'punctuation.definition.typeparameters.begin.cs',
    'punctuation.definition.typeparameters.end.cs',
  ]),
  colorRule('TWILIGHT NEUTRAL PUNCTUATION', color.white, [
    'punctuation.definition.keyword.svelte',
    'keyword.operator.recipe.end.just',
    'storage.modifier.array.bracket.square.c',
    'keyword.control.ternary.java',
  ]),

  // Decorations intentionally own every fontStyle assignment.
  decorationRule('REGULAR', 'regular', [
    // Constants and literals
    'constant.character',
    'constant.character.escape',
    'constant.escape',
    'constant.language',
    'constant.language.boolean.false.js',
    'constant.language.boolean.false.jsx',
    'constant.language.boolean.false.ts',
    'constant.language.boolean.false.tsx',
    'constant.language.boolean.null.js',
    'constant.language.boolean.null.jsx',
    'constant.language.boolean.null.ts',
    'constant.language.boolean.null.tsx',
    'constant.language.boolean.true.js',
    'constant.language.boolean.true.jsx',
    'constant.language.boolean.true.ts',
    'constant.language.boolean.true.tsx',
    'constant.language.boolean.yaml',
    'constant.language.color.rgb-value.css.sass',
    'constant.language.dart',
    'constant.language.json.comments',
    'constant.language.null.js',
    'constant.numeric',
    'constant.numeric.css',
    'constant.numeric.decimal.js',
    'constant.numeric.hex.toml',
    'constant.other.caps.python',
    'constant.other.caps.rust',
    'constant.other.color',
    'constant.other.color.rgb-value.hex',
    'constant.other.color.rgb-value.hex.css',
    'constant.other.date.toml',
    'constant.other.key',
    'constant.other.php',
    'constant.other.reference.link.markdown',
    'constant.other.symbol',
    // Entities and declarations
    'entity.name.function',
    'entity.name.function.close',
    'entity.name.function.css',
    'entity.name.function.dart',
    'entity.name.function.go',
    'entity.name.function.java',
    'entity.name.function.macro.rust',
    'entity.name.function.python',
    'entity.name.function.ruby',
    'entity.name.function.rust',
    'entity.name.function.sass',
    'entity.name.function.scss',
    'entity.name.function.sql',
    'entity.name.function.support.go',
    'entity.name.function.target.just',
    'entity.name.function.target.makefile',
    'entity.name.method.js',
    'entity.name.namespace.rust',
    'entity.name.section.markdown',
    'entity.name.section.toml',
    'entity.name.tag.css',
    'entity.name.tag.css.sass.symbol',
    'entity.name.tag.reference',
    'entity.name.tag.wildcard.css',
    'entity.name.tag.wildcard.sass',
    'entity.name.tag.wildcard.scss',
    'entity.name.tag.yaml',
    'entity.name.typ.dart',
    'entity.name.type',
    'entity.name.type.class.java',
    'entity.name.type.class.js',
    'entity.name.type.class.jsx',
    'entity.name.type.class.python',
    'entity.name.type.class.ts',
    'entity.name.type.class.tsx',
    'entity.name.type.go',
    'entity.name.type.js',
    'entity.name.type.module.js',
    'entity.name.type.numeric.rust',
    'entity.name.type.primitive.rust',
    'entity.name.type.rust',
    'entity.name.type.struct.rust',
    'entity.name.type.struct.swift',
    'entity.name.type.swift',
    'entity.other.attribute-name.attribute.css',
    'entity.other.attribute-name.attribute.sass',
    'entity.other.attribute-name.attribute.scss',
    'entity.other.attribute-name.class',
    'entity.other.attribute-name.class.sass',
    'entity.other.attribute-name.pseudo-class',
    'entity.other.attribute-name.pseudo-class.css',
    'entity.other.attribute-name.pseudo-element.css',
    'entity.other.attribute-selector.sass',
    'entity.other.inherited-class',
    'entity.other.inherited-class.java',
    'entity.other.keyframe-offset.css',
    // Invalid and deprecated code
    'invalid.deprecated',
    // Keywords and operators
    'keyword',
    'keyword.control.default.js.jsx',
    'keyword.control.unit.css.sass',
    'keyword.operator',
    'keyword.operator.arithmetic.java',
    'keyword.operator.arrow.skinny.rust',
    'keyword.operator.assignment',
    'keyword.operator.assignment.compound.js',
    'keyword.operator.assignment.js',
    'keyword.operator.assignment.ts',
    'keyword.operator.assignment.tsx',
    'keyword.operator.borrow.and.rust',
    'keyword.operator.closure.dart',
    'keyword.operator.comparison.css',
    'keyword.operator.comparison.dart',
    'keyword.operator.comparison.java',
    'keyword.operator.comparison.js',
    'keyword.operator.comparison.jsx',
    'keyword.operator.comparison.sass',
    'keyword.operator.comparison.scss',
    'keyword.operator.comparison.ts',
    'keyword.operator.comparison.tsx',
    'keyword.operator.css',
    'keyword.operator.custom.postfix.swift',
    'keyword.operator.expression.of.js',
    'keyword.operator.expression.typeof.js',
    'keyword.operator.function-result.swift',
    'keyword.operator.logical.java',
    'keyword.operator.logical.js',
    'keyword.operator.logical.ts',
    'keyword.operator.logical.tsx',
    'keyword.operator.namespace.rust',
    'keyword.operator.negation.regexp',
    'keyword.operator.new.js',
    'keyword.operator.new.jsx',
    'keyword.operator.new.ts',
    'keyword.operator.new.tsx',
    'keyword.operator.optional.ts',
    'keyword.operator.relational.js',
    'keyword.operator.sass',
    'keyword.operator.scss',
    'keyword.operator.ternary.dart',
    'keyword.operator.type.annotation.ts',
    'keyword.other.crate.rust',
    'keyword.other.create.sql',
    'keyword.other.DDL.create.II.sql',
    'keyword.other.DML.sql',
    'keyword.other.js',
    'keyword.other.LUW.sql',
    'keyword.other.special-method',
    'keyword.other.sql',
    'keyword.other.substitution',
    'keyword.other.template',
    'keyword.other.unit',
    'keyword.other.unit.ch.css',
    'keyword.other.unit.cm.css',
    'keyword.other.unit.deg.css',
    'keyword.other.unit.em.css',
    'keyword.other.unit.ex.css',
    'keyword.other.unit.in.css',
    'keyword.other.unit.mm.css',
    'keyword.other.unit.pc.css',
    'keyword.other.unit.percentage.css',
    'keyword.other.unit.pt.css',
    'keyword.other.unit.px',
    'keyword.other.unit.px.css',
    'keyword.other.unit.rem.css',
    'keyword.other.unit.s',
    'keyword.other.unit.s.css',
    'keyword.other.unit.vh.css',
    'keyword.other.unit.vmax.css',
    'keyword.other.unit.vmin.css',
    'keyword.other.unit.vw.css',
    // Markup
    'markup.changed.git_gutter',
    'markup.heading',
    'markup.heading | markup.heading entity.name',
    'markup.heading.markdown',
    'markup.inserted',
    'markup.inserted.git_gutter',
    'markup.quote punctuation.definition.blockquote.markdown',
    'markup.raw.block',
    'markup.raw.block.fenced.markdown',
    'markup.table',
    'markup.underline.link.markdown',
    // Meta scopes
    'meta.arrow.tsx',
    'meta.at-rule.if',
    'meta.at-rule.mixin',
    'meta.attribute-selector.css',
    'meta.attribute-selector.sass',
    'meta.attribute-selector.scss',
    'meta.attribute.python',
    'meta.attribute.rust',
    'meta.block.js meta.block.js new.expr.js meta.function-call.js',
    'meta.block.js meta.var.expr.js variable.other.object.js',
    'meta.block.js variable.other.object.js',
    'meta.block.jsx meta.block.jsx new.expr.jsx meta.function-call.jsx',
    'meta.block.jsx meta.var.expr.jsx variable.other.object.jsx',
    'meta.block.jsx variable.other.object.jsx',
    'meta.block.ts meta.block.ts new.expr.ts meta.function-call.ts',
    'meta.block.ts meta.var.expr.ts variable.other.object.ts',
    'meta.block.ts variable.other.object.ts',
    'meta.block.tsx',
    'meta.block.tsx meta.block.tsx new.expr.tsx meta.function-call.tsx',
    'meta.block.tsx meta.var.expr.tsx variable.other.object.tsx',
    'meta.block.tsx variable.other.object.tsx',
    'meta.brace.round',
    'meta.brace.square',
    'meta.catch.parameters.java storage.type.java',
    'meta.class-method.js',
    'meta.create.sql',
    'meta.declaration.dart',
    'meta.definition.function',
    'meta.definition.function.body.swift storage.type.function.swift',
    'meta.definition.function.js',
    'meta.definition.method.ts',
    'meta.definition.variable.groovy',
    'meta.definition.variable.java storage.type.generic.java',
    'meta.definition.variable.java storage.type.java',
    'meta.definition.variable.java storage.type.primitive.array.java',
    'meta.definition.variable.name.groovy',
    'meta.embedded.block.github-actions-expression',
    'meta.embedded.expression.dart',
    'meta.embedded.expression.js',
    'meta.embedded.expression.jsx',
    'meta.embedded.expression.ts',
    'meta.embedded.expression.tsx',
    'meta.embedded.line',
    'meta.export.default meta.object.member',
    'meta.export.default.ts meta.array.literal.ts',
    'meta.export.default.ts meta.object.member.ts',
    'meta.field.declaration.ts',
    'meta.field.declaration.tsx',
    'meta.fstring.python',
    'meta.function-call.arguments.python',
    'meta.function-call.java',
    'meta.function-call.js',
    'meta.function-call.jsx',
    'meta.function-call.python',
    'meta.function-call.ruby entity.name.function.ruby',
    'meta.function-call.swift meta.function-call.swift support.function.any-method.swift',
    'meta.function-call.ts',
    'meta.function-call.tsx',
    'meta.function.definition.rust',
    'meta.function.js',
    'meta.function.js meta.block.js meta.function.js meta.block.js meta.block.js variable.other.object.js',
    'meta.function.jsx',
    'meta.function.jsx meta.block.jsx meta.function.jsx meta.block.jsx meta.block.jsx variable.other.object.jsx',
    'meta.function.ts',
    'meta.function.ts meta.block.ts meta.function.ts meta.block.ts meta.block.ts variable.other.object.ts',
    'meta.function.tsx',
    'meta.function.tsx meta.block.tsx meta.function.tsx meta.block.tsx meta.block.tsx variable.other.object.tsx',
    'meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js',
    'meta.import.ts punctuation.definition.block',
    'meta.import.ts punctuation.definition.block.ts',
    'meta.indexed-name.python',
    'meta.jsx.children.js.jsx',
    'meta.method-call.groovy',
    'meta.method.body.java',
    'meta.method.identifier.java storage.type.java',
    'meta.method.identifier.java variable.parameter.java',
    'meta.object-literal.key',
    'meta.object.member',
    'meta.object.member.js',
    'meta.property-list',
    'meta.property-list.css',
    'meta.property-list.css entity.name.tag.css',
    'meta.property-list.css meta.at-rule.include.css',
    'meta.property-list.css variable.css',
    'meta.property-list.css.sass.prop comment',
    'meta.property-list.css.sass.prop keyword.control.unit.css.sass',
    'meta.property-list.sass',
    'meta.property-list.sass entity.name.tag.sass',
    'meta.property-list.sass meta.at-rule.include.sass',
    'meta.property-list.sass variable.sass',
    'meta.property-list.scss',
    'meta.property-list.scss entity.name.tag.scss',
    'meta.property-list.scss meta.at-rule.include.scss',
    'meta.property-list.scss variable.scss',
    'meta.property-name',
    'meta.property-name.css',
    'meta.property-name.sass',
    'meta.property-name.scss',
    'meta.property-value',
    'meta.property-value.css',
    'meta.property-value.css variable.css',
    'meta.property-value.sass',
    'meta.property-value.sass variable.sass',
    'meta.property-value.scss',
    'meta.property-value.scss variable.scss',
    'meta.require.ruby',
    'meta.tag',
    'meta.try.body.java storage.type.java',
    'meta.type-name.swift',
    'meta.type.annotation.ts',
    'meta.type.annotation.tsx',
    'meta.use.php',
    'meta.use.rust',
    'meta.var-single-variable.expr.js',
    'meta.var.expr.js',
    'meta.var.expr.ts',
    'meta.var.expr.ts meta.definition.variable.ts',
    'meta.var.expr.tsx',
    'meta.var.expr.tsx meta.arrow.tsx',
    'meta.var.expr.tsx meta.block.tsx',
    'meta.var.expr.tsx meta.definition.variable.tsx',
    // Other language scopes
    'other.source.dart',
    // Properties
    'property.value.dotenv',
    // Punctuation
    'punctuation',
    'punctuation.accessor.js',
    'punctuation.accessor.jsx',
    'punctuation.accessor.ts',
    'punctuation.accessor.tsx',
    'punctuation.bracket.angle.java',
    'punctuation.brackets.angle.rust',
    'punctuation.brackets.attribute.rust',
    'punctuation.brackets.curly.rust',
    'punctuation.brackets.round.rust',
    'punctuation.comma.rust',
    'punctuation.definition.attribute-selector.begin.bracket.square',
    'punctuation.definition.attribute-selector.end.bracket.square',
    'punctuation.definition.block.js',
    'punctuation.definition.block.tsx',
    'punctuation.definition.bold.markdown',
    'punctuation.definition.character-class.regexp',
    'punctuation.definition.constant',
    'punctuation.definition.constant.css',
    'punctuation.definition.constant.markdown',
    'punctuation.definition.dictionary.begin.json.comments',
    'punctuation.definition.entity',
    'punctuation.definition.entity.css',
    'punctuation.definition.fenced.markdown',
    'punctuation.definition.interpolation.begin.bracket.curly.css',
    'punctuation.definition.interpolation.begin.bracket.curly.sass',
    'punctuation.definition.interpolation.begin.bracket.curly.scss',
    'punctuation.definition.interpolation.end.bracket.curly.css',
    'punctuation.definition.interpolation.end.bracket.curly.sass',
    'punctuation.definition.interpolation.end.bracket.curly.scss',
    'punctuation.definition.list_item.markdown',
    'punctuation.definition.map.begin.bracket.round.scss',
    'punctuation.definition.map.end.bracket.round.scss',
    'punctuation.definition.parameters.begin.bracket.round.scss',
    'punctuation.definition.parameters.begin.js',
    'punctuation.definition.parameters.end.bracket.round.scss',
    'punctuation.definition.parameters.end.js',
    'punctuation.definition.string',
    'punctuation.definition.string.begin.css',
    'punctuation.definition.string.begin.html',
    'punctuation.definition.string.begin.js',
    'punctuation.definition.string.end.css',
    'punctuation.definition.string.end.html',
    'punctuation.definition.string.end.js',
    'punctuation.definition.tag',
    'punctuation.definition.tag.begin.html',
    'punctuation.definition.tag.end.html',
    'punctuation.definition.tag.html',
    'punctuation.definition.template-expression',
    'punctuation.dot.dart',
    'punctuation.section.class.end',
    'punctuation.section.embedded',
    'punctuation.section.function.begin.bracket.round.css',
    'punctuation.section.function.end.bracket.round.css',
    'punctuation.section.function.scss',
    'punctuation.section.property-list.begin.bracket.curly.css',
    'punctuation.section.property-list.begin.bracket.curly.sass',
    'punctuation.section.property-list.begin.bracket.curly.scss',
    'punctuation.section.property-list.end.bracket.curly.css',
    'punctuation.section.property-list.end.bracket.curly.sass',
    'punctuation.section.property-list.end.bracket.curly.scss',
    'punctuation.section.scope.begin.c4',
    'punctuation.section.scope.begin.swift',
    'punctuation.section.scope.end.c4',
    'punctuation.section.scope.end.swift',
    'punctuation.semi.rust',
    'punctuation.separator.comma',
    'punctuation.separator.comma.js',
    'punctuation.separator.delimiter.java',
    'punctuation.separator.inheritance.php',
    'punctuation.separator.java',
    'punctuation.separator.key-value.css',
    'punctuation.separator.key-value.html',
    'punctuation.separator.key-value.js',
    'punctuation.separator.key-value.mapping.yaml',
    'punctuation.separator.list.comma.css',
    'punctuation.separator.period.java',
    'punctuation.terminator.dart',
    'punctuation.terminator.java',
    'punctuation.terminator.rule.css',
    'punctuation.terminator.rule.sass',
    'punctuation.terminator.rule.scss',
    'punctuation.terminator.statement.js',
    'punctuation.terminator.statement.ts',
    'punctuation.terminator.statement.tsx',
    // Source roots
    'source.css',
    'source.css.sass',
    'source.css.scss',
    'source.dart',
    'source.go',
    'source.groovy',
    'source.java',
    'source.js',
    'source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
    'source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
    'source.json meta.structure.dictionary.json support.type.property-name.json',
    'source.just',
    'source.makefile',
    'source.python',
    'source.ruby',
    'source.rust',
    'source.sass',
    'source.sass keyword.control',
    'source.sql',
    // Storage declarations
    'storage.modifier',
    'storage.modifier.import.java',
    'storage.modifier.package.java',
    'storage.modifier.sql',
    'storage.type.boolean.go',
    'storage.type.function.arrow',
    'storage.type.groovy',
    'storage.type.numeric.go',
    'storage.type.primitive.dart',
    'storage.type.primitive.java',
    'storage.type.sql',
    'storage.type.string.go',
    // Strings
    'string',
    'string constant.other.placeholder',
    'string.interpolated.single.dart',
    'string.interpolated.single.dart meta.embedded.expression.dart variable.parameter.dart',
    'string.interpolated.single.dart variable.parameter.dart',
    'string.json.comments',
    'string.other.link',
    'string.other.link.description.title.markdown',
    'string.other.link.title.markdown',
    'string.regexp',
    'string.regexp.js',
    'string.regexp.ts',
    // Support symbols
    'support.class',
    'support.class.builtin.js',
    'support.class.dart',
    'support.constant',
    'support.constant.font-name',
    'support.constant.mathematical-symbols.css',
    'support.constant.mathematical-symbols.sass',
    'support.constant.mathematical-symbols.scss',
    'support.constant.property-value',
    'support.constant.property-value.css',
    'support.function',
    'support.function.any-method.swift',
    'support.function.calc.css',
    'support.function.github-actions-expression',
    'support.function.magic.python',
    'support.function.misc.css',
    'support.function.misc.sass',
    'support.function.misc.scss',
    'support.function.name.sass.library',
    'support.function.target.PHONY.makefile',
    'support.orther.namespace.use.php',
    'support.other.namespace.php',
    'support.other.variable',
    'support.type',
    'support.type.builtin.ts',
    'support.type.builtin.tsx',
    'support.type.exception.python',
    'support.type.object.module.js',
    'support.type.property-name.css',
    'support.type.property-name.css meta.property-value.css',
    'support.type.property-name.css.sass.prop.name',
    'support.type.property-name.media.css',
    'support.type.property-name.sass meta.property-value.sass',
    'support.type.property-name.scss meta.property-value.scss',
    'support.type.python',
    'support.type.sys-types',
    'support.variable.property.js',
    'support.variable.property.tsx',
    'support.variable.property.tx',
    // Text
    'text.html.markdown',
    'text.html.markdown markup.inline.raw.markdown',
    'text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown',
    // Variables
    'variable.argument.css',
    'variable.css',
    'variable.function',
    'variable.function.constructor',
    'variable.key.dotenv',
    'variable.language',
    'variable.language.arguments.js',
    'variable.language.expanded-namespace.css',
    'variable.language.expanded-namespace.sass',
    'variable.language.expanded-namespace.scss',
    'variable.language.fenced.markdown',
    'variable.language.ruby',
    'variable.language.this',
    'variable.object.property.js',
    'variable.object.property.ts',
    'variable.object.property.tsx',
    'variable.other',
    'variable.other.assignment.go',
    'variable.other.block.ruby',
    'variable.other.constant.js',
    'variable.other.constant.jsx',
    'variable.other.constant.object.js',
    'variable.other.constant.object.jsx',
    'variable.other.constant.object.ts',
    'variable.other.constant.object.tsx',
    'variable.other.constant.property.js',
    'variable.other.constant.property.jsx',
    'variable.other.constant.property.ts',
    'variable.other.constant.property.tsx',
    'variable.other.constant.ruby',
    'variable.other.constant.ts',
    'variable.other.constant.tsx',
    'variable.other.env',
    'variable.other.go',
    'variable.other.just',
    'variable.other.key.toml',
    'variable.other.makefile',
    'variable.other.object.java',
    'variable.other.object.js',
    'variable.other.object.jsx',
    'variable.other.object.property',
    'variable.other.object.property.js',
    'variable.other.object.property.tsx',
    'variable.other.object.ts',
    'variable.other.object.tsx',
    'variable.other.property',
    'variable.other.property.go',
    'variable.other.read.github-actions-expression',
    'variable.other.readwrite.alias.js',
    'variable.other.readwrite.alias.ts',
    'variable.other.readwrite.alias.tsx',
    'variable.other.readwrite.js',
    'variable.other.readwrite.ts',
    'variable.other.readwrite.tsx',
    'variable.other.rust',
    'variable.other.swift',
    'variable.parameter',
    'variable.parameter.function.language.special',
    'variable.parameter.js',
    'variable.parameter.ts',
    'variable.parameter.tsx',
    'variable.parameter.url',
    'variable.parameter.url.scss',
    'variable.ruby',
    'variable.sass',
    'variable.scss',
    // Compound and wildcard selectors
    'operator',
  ]),
  decorationRule('BOLD', 'bold', [
    // Markup
    'markup.bold',
    'markup.bold markup.italic',
    'markup.bold markup.italic string',
    'markup.bold string',
    'markup.bold.markdown',
    'markup.changed',
    'markup.italic markup.bold',
    'markup.italic markup.bold string',
    'markup.quote markup.bold',
    'markup.quote markup.bold string',
    // Meta scopes
    'meta.separator',
  ]),
  decorationRule('ITALIC', 'italic', [
    // Comments and documentation
    'comment',
    'comment.block.documentation.dart variable.name.source.dart',
    'comment.block.documentation.dart variable.other.source.dart',
    'comment.line.number-sign.yaml entity.name.tag.yaml',
    'comment.line.number-sign.yaml meta.embedded.block.github-actions-expression',
    'comment.line.number-sign.yaml punctuation.separator.key-value.mapping.yaml',
    'comment.line.number-sign.yaml string',
    'comment.line.number-sign.yaml variable.other.read.github-actions-expression',
    'comment.line.shebang.js',
    // Entities and declarations
    'entity.name.type.package.go',
    'entity.other.attribute-name',
    // Keywords and operators
    'keyword.control.at-rule.font-face.css',
    'keyword.control.at-rule.import',
    'keyword.control.at-rule.import.css',
    'keyword.control.at-rule.include.css',
    'keyword.control.at-rule.include.sass',
    'keyword.control.at-rule.include.scss',
    'keyword.control.at-rule.keyframes.css',
    'keyword.control.at-rule.keyframes.sass',
    'keyword.control.at-rule.keyframes.scss',
    'keyword.control.at-rule.media',
    'keyword.control.at-rule.media.css',
    'keyword.control.at-rule.mixin',
    'keyword.control.at-rule.supports.css',
    'keyword.control.at-rule.use.scss',
    'keyword.control.await.swift',
    'keyword.control.c',
    'keyword.control.catch-exception.dart',
    'keyword.control.catch.java',
    'keyword.control.conditional.js',
    'keyword.control.conditional.jsx',
    'keyword.control.conditional.ts',
    'keyword.control.conditional.tsx',
    'keyword.control.dart',
    'keyword.control.exception.swift',
    'keyword.control.export.js',
    'keyword.control.export.jsx',
    'keyword.control.export.ts',
    'keyword.control.export.tsx',
    'keyword.control.flow.js',
    'keyword.control.flow.jsx',
    'keyword.control.flow.python',
    'keyword.control.flow.ts',
    'keyword.control.flow.tsx',
    'keyword.control.from.js',
    'keyword.control.from.jsx',
    'keyword.control.from.ts',
    'keyword.control.from.tsx',
    'keyword.control.go',
    'keyword.control.groovy',
    'keyword.control.if.css',
    'keyword.control.if.css punctuation.definition.keyword.css',
    'keyword.control.if.sass',
    'keyword.control.if.sass punctuation.definition.keyword.sass',
    'keyword.control.if.scss',
    'keyword.control.if.scss punctuation.definition.keyword.scss',
    'keyword.control.import.go',
    'keyword.control.import.js',
    'keyword.control.import.jsx',
    'keyword.control.import.python',
    'keyword.control.import.ts',
    'keyword.control.import.tsx',
    'keyword.control.java',
    'keyword.control.loop.js',
    'keyword.control.new.groovy',
    'keyword.control.new.java',
    'keyword.control.operator',
    'keyword.control.pseudo-method.ruby',
    'keyword.control.return.css punctuation.definition.keyword.css',
    'keyword.control.return.dart',
    'keyword.control.return.sass',
    'keyword.control.return.sass punctuation.definition.keyword.sass',
    'keyword.control.return.scss',
    'keyword.control.return.scss punctuation.definition.keyword.scss',
    'keyword.control.ruby',
    'keyword.control.rust',
    'keyword.control.start-block.ruby',
    'keyword.control.transfer.swift',
    'keyword.control.try.java',
    'keyword.control.trycatch.js',
    'keyword.control.trycatch.jsx',
    'keyword.control.trycatch.ts',
    'keyword.control.trycatch.tsx',
    'keyword.declaration.dart',
    'keyword.control.directive.include.c',
    'keyword.function.go',
    'keyword.go.mod',
    'keyword.operator.instanceof.java',
    'keyword.operator.logical.python',
    'keyword.other.declaration-specifier.accessibility.swift',
    'keyword.other.declaration-specifier.swift',
    'keyword.other.fn.rust',
    'keyword.other.import.dart',
    'keyword.other.import.java',
    'keyword.other.package.java',
    'keyword.other.rust',
    'keyword.other.special-method.ruby',
    'keyword.other.typedef.c',
    'keyword.package.go',
    'keyword.struct.go',
    'keyword.type.go',
    'keyword.var.go',
    // Markup
    'markup.italic',
    'markup.quote',
    // Meta scopes
    'meta.at-rule.function.css',
    'meta.at-rule.function.sass',
    'meta.at-rule.function.scss',
    'meta.at-rule.include.css',
    'meta.at-rule.include.sass',
    'meta.at-rule.include.scss',
    'meta.at-rule.keyframes.css',
    'meta.at-rule.keyframes.sass',
    'meta.at-rule.keyframes.scss',
    'meta.at-rule.supports.css',
    'meta.at-rule.supports.sass',
    'meta.at-rule.supports.scss',
    'meta.at-rule.use.css',
    'meta.at-rule.use.sass',
    'meta.at-rule.use.scss',
    'meta.definition.variable.css',
    'meta.definition.variable.sass',
    'meta.definition.variable.scss',
    'meta.export.default',
    'meta.export.default.ts',
    'meta.function.decorator.python',
    'meta.function.decorator.python support.type.python',
    'meta.import',
    'meta.import.ts',
    'meta.tag.metadata.doctype.html entity.name.tag',
    'meta.tag.metadata.doctype.html entity.other.attribute-name.html',
    'meta.tag.metadata.doctype.html punctuation.definition.tag.begin.html',
    'meta.tag.metadata.doctype.html punctuation.definition.tag.end.html',
    // Punctuation
    'punctuation.definition.annotation.java',
    'punctuation.definition.comment.go.mod',
    'punctuation.definition.keyword',
    'punctuation.definition.keyword.css',
    'punctuation.definition.directive.c',
    // Storage declarations
    'storage.modifier.async.swift',
    'storage.modifier.attribute.swift',
    'storage.modifier.c',
    'storage.modifier.dart',
    'storage.modifier.exception.swift',
    'storage.modifier.implements.java',
    'storage.modifier.java',
    'storage.modifier.mut.rust',
    'storage.modifier.swift',
    'storage.modifier.ts',
    'storage.modifier.tsx',
    'storage.type',
    'storage.type.annotation.dart',
    'storage.type.annotation.java',
    'storage.type.class.python',
    'storage.type.def.groovy',
    'storage.type.function',
    'storage.type.function.python',
    'storage.type.rust',
    // Tags
    'tag.decorator.js entity.name.tag.js',
    'tag.decorator.js punctuation.definition.tag.js',
    // Text
    'text.html.basic entity.other.attribute-name',
    'text.html.basic entity.other.attribute-name.html',
    // Variables
    'variable.language.dart',
    'variable.language.self.rust',
    'variable.language.special.self.python',
    'variable.language.this.java',
  ]),
  decorationRule('UNDERLINE', 'underline', [
    // Markup
    'markup.underline',
    // Compound and wildcard selectors
    '*link*',
    '*uri*',
    '*url*',
  ]),
];

/**
 * Dart's semantic keyword fallback clears TextMate italics. Keep typography
 * separate from the semantic palette, just like the TextMate layers above.
 */
const semanticDecorations = {
  'keyword:dart': { italic: true },
  'keyword.void:dart': { italic: false },
};

function resolveTheme({ name, italics = true }) {
  const theme = {
    name: name,
    type: 'dark',
    colors: {
      'materialTheme.accent': color.green,
      focusBorder: color.focus,
      foreground: color.white,
      // ACTIVITY BAR
      'activityBarBadge.background': color.green,
      'activityBar.background': color.background,
      'activityBar.dropBackground': color.background,
      'activityBar.foreground': color.white,
      'activityBar.border': color.background,
      'activityBarBadge.foreground': color.white,
      // BUTTON
      'button.background': color.control,
      'button.hoverBackground': color.greenHover,
      'button.foreground': color.white,
      // DROPDOWN
      'dropdown.background': color.background,
      'dropdown.border': color.background,
      'dropdown.foreground': color.white,
      // EDITOR
      'editor.background': color.background,
      'editor.foreground': color.white, // #eeffff
      'editorCursor.foreground': color.white,
      'editor.lineHighlightBackground': color.background, // Подсветка линии
      'editorWidget.resizeBorder': color.green,
      'editorWidget.border': color.green,
      'editorGutter.background': color.background,
      'editorLineNumber.foreground': color.lineNumber,
      'editorLineNumber.activeForeground': color.control,
      // Preserve syntax colors, including interpolation and type brackets,
      // even when the user's bracket pair colorization setting is enabled.
      'editorBracketHighlight.foreground1': color.transparent,
      'editorBracketHighlight.foreground2': color.transparent,
      'editorBracketHighlight.foreground3': color.transparent,
      'editorBracketHighlight.foreground4': color.transparent,
      'editorBracketHighlight.foreground5': color.transparent,
      'editorBracketHighlight.foreground6': color.transparent,
      'editorIndentGuide.activeBackground1': color.border, // Линия кода
      'editorIndentGuide.background1': color.background, // Линия кода
      'tree.indentGuidesStroke': color.background,
      // INPUT
      'input.background': color.background,
      'input.errorBackground': color.error,
      'input.border': color.background,
      'input.activeBorder': color.background,
      'input.errorBorder': color.error,
      'input.foreground': color.white,
      'input.placeholderForeground': color.muted,
      'inputOption.activeBorder': color.activeInputBorder,
      // LIST
      'list.activeSelectionForeground': color.green,
      'list.inactiveSelectionForeground': color.green,
      'list.highlightForeground': color.green,
      // PANEL
      'panel.background': color.background,
      'panel.border': color.background,
      'panel.activeBorder': color.green,
      'panel.activeForeground': color.white,
      'panel.inactiveForeground': color.white,
      // SIDEBAR
      'sideBar.background': color.background,
      'sideBar.foreground': color.muted,
      'sideBar.border': color.background,
      'sideBarTitle.foreground': color.muted,
      'sideBarSectionHeader.background': color.background,
      'sideBarSectionHeader.foreground': color.muted,
      // STATUS BAR
      'statusBar.background': color.background,
      'statusBar.foreground': color.muted,
      'statusBar.border': color.background,
      'statusBar.debuggingBackground': color.background,
      // TABS
      'tab.activeBackground': color.surface,
      'tab.activeForeground': color.white,
      'tab.inactiveBackground': color.background,
      'tab.inactiveForeground': color.white,
      'tab.border': color.background,
      'tab.activeBorder': color.green,
      // EDITOR GROUP
      'editorGroup.emptyBackground': color.background,
      'editorGroupHeader.tabsBorder': color.background,
      'editorGroupHeader.tabsBackground': color.background,
      // TITLEBAR
      'titleBar.activeBackground': color.background,
      'titleBar.activeForeground': color.muted,
      'scrollbar.shadow': color.background,
      'widget.shadow': color.background,
      // TERMINAL
      'terminal.ansiBlack': color.terminalBlack,
      'terminal.ansiBrightBlack': color.surface,
      'terminal.ansiBlue': color.border,
      'terminal.ansiGreen': color.white,
      'terminal.ansiWhite': color.white,
      // "terminal.ansiBrightBlue":"#0D6678",
      // "terminal.ansiBrightCyan":"#8BA59B",
      // "terminal.ansiBrightGreen":color.green,
      // "terminal.ansiBrightMagenta":"#8F4673",
      // "terminal.ansiBrightRed":"#FB543F",
      // "terminal.ansiBrightWhite":color.white,
      // "terminal.ansiBrightYellow":"#FAC03B",
      // "terminal.ansiCyan":"#8BA59B",
      // "terminal.ansiMagenta":"#8F4673",
      // "terminal.ansiRed":"#FB543F",
      // "terminal.ansiYellow":"#FAC03B",
      'terminal.background': color.background,
      // "terminal.foreground": color.muted,
      // GIT
      'gitDecoration.ignoredResourceForeground': color.ignored,
      'scrollbarSlider.activeBackground': color.greenAlpha50,
      'progressBar.background': color.green,
      'editorSuggestWidget.highlightForeground': color.green,
      'textLink.foreground': color.green,
      'pickerGroup.foreground': color.green,
      'notificationLink.foreground': color.green,
      'settings.modifiedItemIndicator': color.green,
      'settings.headerForeground': color.green,
      'breadcrumb.activeSelectionForeground': color.green,
      'menu.selectionForeground': color.white,
      'menubar.selectionForeground': color.white,
      'panelTitle.activeBorder': color.green,
      // DART COLORS
      'dart.closingLabels': color.gray,
    },
    // Original omits the dedicated italic layer; Ligatures retains it. Regular,
    // bold, underline, and every foreground rule remain byte-for-byte equal.
    tokenColors: italics
      ? tokenColors
      : tokenColors.filter((rule) => rule.name !== 'ITALIC'),
    semanticHighlighting: true,
    semanticTokenColors: {
      // Color palette only; semantic typography is merged separately below.
      namespace: color.yellow,
      type: color.white,
      class: color.white,
      interface: color.white,
      enum: color.white,
      struct: color.white,
      typeParameter: color.white,
      'class.declaration': color.blue,
      'interface.declaration': color.blue,
      'enum.declaration': color.blue,
      'struct.declaration': color.blue,
      parameter: color.blue,
      variable: color.blue,
      'variable.defaultLibrary': color.yellow,
      property: color.purple,
      enumMember: color.purple,
      'enumMember.declaration': color.blue,
      function: color.yellow,
      'function.declaration': color.blue,
      'function.definition': color.blue,
      'function.local': color.blue,
      method: color.purple,
      event: color.purple,
      macro: color.yellow,
      'macro.declaration': color.blue,
      decorator: color.yellow,
      label: color.yellow,
      keyword: color.yellow,
      'keyword:dart': color.yellow,
      'keyword.void:dart': color.white,
      boolean: color.yellow,
      number: color.orange,
      string: color.green,
      regexp: color.green,
      comment: color.gray,
      operator: color.operator,
      // Dart exposes constructor and import-prefix contexts that TS omits.
      'class.constructor:dart': color.yellow,
      'class.constructor.declaration:dart': color.blue,
      'variable.importPrefix:dart': color.yellow,
      'variable.instance:dart': color.purple,
      'annotation:dart': color.yellow,
      'source.interpolation:dart': color.green,
      'property.annotation:dart': color.yellow,
      'function:just': color.purple,
      'function.declaration:just': color.purple,
      'function.definition:just': color.purple,
      'function:makefile': color.purple,
      'function.declaration:makefile': color.purple,
      'function.definition:makefile': color.purple,
      // The built-in JS/TS provider exposes the non-standard local modifier.
      // Do not infer local/global identity from TextMate nesting depth.
      ...Object.fromEntries(
        [
          'javascript',
          'javascriptreact',
          'typescript',
          'typescriptreact',
        ].flatMap((language) => [
          ...['variable', 'function'].flatMap((type) => [
            [`${type}:${language}`, color.yellow],
            [`${type}.declaration:${language}`, color.blue],
            [`${type}.local:${language}`, color.blue],
          ]),
          [`parameter:${language}`, color.blue],
          [`property:${language}`, color.purple],
          [`method:${language}`, color.purple],
        ]),
      ),
      'class:javascript': color.yellow,
      'class:javascriptreact': color.yellow,
    },
  };

  for (const [selector, decoration] of Object.entries(semanticDecorations)) {
    if (!italics && decoration.italic === true) continue;
    theme.semanticTokenColors[selector] = {
      foreground: theme.semanticTokenColors[selector],
      ...decoration,
    };
  }
  return theme;
}

module.exports = resolveTheme;
